package cli

import (
	"context"
	"io"
	"net"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func readDropIn(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}

func TestWriteExposeDropIn(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name       string
		existing   string   // drop-in content before the call ("" = absent)
		path       string   // path being exposed
		want       []string // lines that must appear, in order
		wantSecond bool     // whether a second identical call must report a change
	}{
		{
			name: "new file for a plain worktree",
			path: "/srv/ghost",
			want: []string{"[Service]", "ReadWritePaths=/srv/ghost"},
		},
		{
			name: "idempotent for a plain worktree",
			path: "/srv/ghost",
			want: []string{"ReadWritePaths=/srv/ghost"},
		},
		{
			name: "rootless socket also relaxes ProtectHome",
			path: "/run/user/1000/docker.sock",
			want: []string{
				"[Service]",
				"ReadWritePaths=/run/user/1000/docker.sock",
				"ProtectHome=read-only",
			},
		},
		{
			name: "home worktree also relaxes ProtectHome",
			path: "/home/deploy/project",
			want: []string{"ReadWritePaths=/home/deploy/project", "ProtectHome=read-only"},
		},
		{
			name: "existing lines are preserved",
			existing: "# Generated by scripts/install.sh (--read-write/--home-read).\n" +
				"[Service]\nReadWritePaths=/srv/other\n",
			path: "/srv/ghost",
			want: []string{
				"# Generated by scripts/install.sh (--read-write/--home-read).",
				"[Service]",
				"ReadWritePaths=/srv/other",
				"ReadWritePaths=/srv/ghost",
			},
		},
		{
			name:     "hand-made file without a section header gains one",
			existing: "ReadWritePaths=/srv/other\n",
			path:     "/srv/ghost",
			want:     []string{"[Service]", "ReadWritePaths=/srv/other", "ReadWritePaths=/srv/ghost"},
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			dropIn := filepath.Join(t.TempDir(), "yukariko.service.d", "10-writables.conf")
			if tc.existing != "" {
				if err := os.MkdirAll(filepath.Dir(dropIn), 0o755); err != nil {
					t.Fatal(err)
				}
				if err := os.WriteFile(dropIn, []byte(tc.existing), 0o644); err != nil {
					t.Fatal(err)
				}
			}

			changed, err := writeExposeDropIn(dropIn, tc.path)
			if err != nil || !changed {
				t.Fatalf("first write: changed=%v err=%v", changed, err)
			}
			content := readDropIn(t, dropIn)
			pos := 0
			for _, want := range tc.want {
				idx := strings.Index(content[pos:], want+"\n")
				if idx < 0 {
					t.Fatalf("missing (or out of order) %q in:\n%s", want, content)
				}
				pos += idx + len(want) + 1
			}

			// The second identical call must be a no-op, byte-identical.
			before := content
			changed, err = writeExposeDropIn(dropIn, tc.path)
			if err != nil || changed {
				t.Fatalf("second write: changed=%v err=%v; want idempotent", changed, err)
			}
			if readDropIn(t, dropIn) != before {
				t.Fatal("idempotent rerun changed the file")
			}
		})
	}
}

func TestRunExpose(t *testing.T) {
	t.Run("non-root is refused with guidance", func(t *testing.T) {
		app := NewApp()
		app.euid = func() int { return 1000 }
		err := app.Execute(context.Background(), []string{"expose", "/srv/ghost"}, io.Discard, io.Discard)
		if err == nil || !strings.Contains(err.Error(), "root") {
			t.Fatalf("err = %v, want a root guidance error", err)
		}
	})

	t.Run("git worktree from cwd, socket from arg", func(t *testing.T) {
		reloadCalled := false
		origReload := daemonReload
		t.Cleanup(func() { daemonReload = origReload })
		daemonReload = func(context.Context) error { reloadCalled = true; return nil }

		unit := filepath.Join(t.TempDir(), "yukariko.service")
		project := t.TempDir()
		if err := os.WriteFile(filepath.Join(project, ".git"), []byte("gitdir: /elsewhere\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		socketPath := filepath.Join(t.TempDir(), "docker.sock")
		ln, err := net.Listen("unix", socketPath)
		if err != nil {
			t.Fatal(err)
		}
		t.Cleanup(func() { _ = ln.Close() })

		app := NewApp()
		app.euid = func() int { return 0 }
		cwd, err := os.Getwd()
		if err != nil {
			t.Fatal(err)
		}
		if err := os.Chdir(project); err != nil {
			t.Fatal(err)
		}
		t.Cleanup(func() { _ = os.Chdir(cwd) })

		if err := app.Execute(context.Background(), []string{"expose", "--unit", unit}, io.Discard, io.Discard); err != nil {
			t.Fatalf("expose from cwd: %v", err)
		}
		if err := app.Execute(context.Background(), []string{"expose", "--unit", unit, socketPath}, io.Discard, io.Discard); err != nil {
			t.Fatalf("expose socket: %v", err)
		}
		if !reloadCalled {
			t.Fatal("daemon-reload never ran")
		}
		content := readDropIn(t, filepath.Join(unit+".d", "10-writables.conf"))
		// Both entries share one drop-in. ProtectHome relaxation is pinned
		// by the writeExposeDropIn table tests (real /run/user and /home
		// prefixes); the temp-dir socket here intentionally does not trip it.
		for _, want := range []string{"ReadWritePaths=" + project, "ReadWritePaths=" + socketPath} {
			if !strings.Contains(content, want) {
				t.Fatalf("drop-in missing %q:\n%s", want, content)
			}
		}
	})

	t.Run("non-git directory is a usage error", func(t *testing.T) {
		app := NewApp()
		app.euid = func() int { return 0 }
		err := app.Execute(context.Background(), []string{"expose", t.TempDir()}, io.Discard, io.Discard)
		if err == nil || !strings.Contains(err.Error(), "git worktree") {
			t.Fatalf("err = %v, want a git-worktree usage error", err)
		}
	})
}
