package cli

import (
	"context"
	"errors"
	"io"
	"net"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

func readDropIn(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}

func TestWriteExposeDropIn(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name       string
		existing   string   // drop-in content before the call ("" = absent)
		path       string   // path being exposed
		want       []string // lines that must appear, in order
		wantSecond bool     // whether a second identical call must report a change
	}{
		{
			name: "new file for a plain worktree",
			path: "/srv/ghost",
			want: []string{"[Service]", "ReadWritePaths=/srv/ghost"},
		},
		{
			name: "idempotent for a plain worktree",
			path: "/srv/ghost",
			want: []string{"ReadWritePaths=/srv/ghost"},
		},
		{
			name: "rootless socket also relaxes ProtectHome",
			path: "/run/user/1000/docker.sock",
			want: []string{
				"[Service]",
				"ReadWritePaths=/run/user/1000/docker.sock",
				"ProtectHome=read-only",
			},
		},
		{
			name: "home worktree also relaxes ProtectHome",
			path: "/home/deploy/project",
			want: []string{"ReadWritePaths=/home/deploy/project", "ProtectHome=read-only"},
		},
		{
			name: "root worktree also relaxes ProtectHome",
			path: "/root/project",
			want: []string{"ReadWritePaths=/root/project", "ProtectHome=read-only"},
		},
		{
			name:     "entries land inside the Service section, not after a later header",
			existing: "[Service]\nReadWritePaths=/srv/other\n[Install]\nWantedBy=multi-user.target\n",
			path:     "/srv/ghost",
			want: []string{
				"[Service]",
				"ReadWritePaths=/srv/ghost",
				"ReadWritePaths=/srv/other",
				"[Install]",
				"WantedBy=multi-user.target",
			},
		},
		{
			name:     "entry present but ProtectHome missing is repaired",
			existing: "[Service]\nReadWritePaths=/home/deploy/project\n",
			path:     "/home/deploy/project",
			want:     []string{"[Service]", "ProtectHome=read-only", "ReadWritePaths=/home/deploy/project"},
		},
		{
			name: "existing lines are preserved",
			existing: "# Generated by scripts/install.sh (--read-write/--home-read).\n" +
				"[Service]\nReadWritePaths=/srv/other\n",
			path: "/srv/ghost",
			want: []string{
				"# Generated by scripts/install.sh (--read-write/--home-read).",
				"[Service]",
				"ReadWritePaths=/srv/ghost",
				"ReadWritePaths=/srv/other",
			},
		},
		{
			name:     "hand-made file without a section header gains one",
			existing: "ReadWritePaths=/srv/other\n",
			path:     "/srv/ghost",
			want:     []string{"[Service]", "ReadWritePaths=/srv/ghost", "ReadWritePaths=/srv/other"},
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			dropIn := filepath.Join(t.TempDir(), "yukariko.service.d", "10-writables.conf")
			if tc.existing != "" {
				if err := os.MkdirAll(filepath.Dir(dropIn), 0o755); err != nil {
					t.Fatal(err)
				}
				if err := os.WriteFile(dropIn, []byte(tc.existing), 0o644); err != nil {
					t.Fatal(err)
				}
			}

			changed, err := writeExposeDropIn(dropIn, tc.path)
			if err != nil || !changed {
				t.Fatalf("first write: changed=%v err=%v", changed, err)
			}
			content := readDropIn(t, dropIn)
			pos := 0
			for _, want := range tc.want {
				idx := strings.Index(content[pos:], want+"\n")
				if idx < 0 {
					t.Fatalf("missing (or out of order) %q in:\n%s", want, content)
				}
				pos += idx + len(want) + 1
			}

			// The second identical call must be a no-op, byte-identical.
			before := content
			changed, err = writeExposeDropIn(dropIn, tc.path)
			if err != nil || changed {
				t.Fatalf("second write: changed=%v err=%v; want idempotent", changed, err)
			}
			if readDropIn(t, dropIn) != before {
				t.Fatal("idempotent rerun changed the file")
			}
		})
	}
}

// The production daemonReload must surface real systemctl failures: the
// runner reserves its error for request validation, so process outcomes
// live on Result.Status and a discard would report "applied" after a
// failed reload.
func TestDaemonReloadSurfacesFailures(t *testing.T) {
	shimDir := t.TempDir()
	writeShim := func(body string) {
		if err := os.WriteFile(filepath.Join(shimDir, "systemctl"), []byte(body), 0o755); err != nil {
			t.Fatal(err)
		}
	}
	t.Setenv("PATH", shimDir+":"+os.Getenv("PATH"))

	writeShim("#!/bin/sh\necho 'boom: unit not found' >&2\nexit 1\n")
	err := daemonReload(context.Background())
	if err == nil || !strings.Contains(err.Error(), "boom") {
		t.Fatalf("err = %v, want the systemctl failure surfaced", err)
	}

	writeShim("#!/bin/sh\nexit 0\n")
	if err := daemonReload(context.Background()); err != nil {
		t.Fatalf("successful reload = %v, want nil", err)
	}
}

func TestRunExpose(t *testing.T) {
	t.Run("non-root is refused with guidance", func(t *testing.T) {
		app := NewApp()
		app.euid = func() int { return 1000 }
		err := app.Execute(context.Background(), []string{"expose", "/srv/ghost"}, io.Discard, io.Discard)
		if err == nil || !strings.Contains(err.Error(), "root") {
			t.Fatalf("err = %v, want a root guidance error", err)
		}
	})

	t.Run("git worktree from cwd, socket from arg, rerun heals", func(t *testing.T) {
		reloads := 0
		origReload := daemonReload
		t.Cleanup(func() { daemonReload = origReload })
		daemonReload = func(context.Context) error { reloads++; return nil }
		origAvail, origUser := aclAvailable, unitUser
		t.Cleanup(func() { aclAvailable, unitUser = origAvail, origUser })
		aclAvailable = func() bool { return true }
		unitUser = func(context.Context, string) (string, error) { return "root", nil } // no ACLs here

		unit := filepath.Join(t.TempDir(), "yukariko.service")
		if err := os.WriteFile(unit, []byte("[Unit]\nDescription=test\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		project := t.TempDir()
		if err := os.WriteFile(filepath.Join(project, ".git"), []byte("gitdir: /elsewhere\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		socketPath := filepath.Join(t.TempDir(), "docker.sock")
		ln, err := net.Listen("unix", socketPath)
		if err != nil {
			t.Fatal(err)
		}
		t.Cleanup(func() { _ = ln.Close() })

		app := NewApp()
		app.euid = func() int { return 0 }
		cwd, err := os.Getwd()
		if err != nil {
			t.Fatal(err)
		}
		if err := os.Chdir(project); err != nil {
			t.Fatal(err)
		}
		t.Cleanup(func() { _ = os.Chdir(cwd) })

		run := func(args ...string) {
			t.Helper()
			all := append([]string{"expose", "--unit", unit}, args...)
			if err := app.Execute(context.Background(), all, io.Discard, io.Discard); err != nil {
				t.Fatalf("expose %v: %v", args, err)
			}
		}
		run()           // worktree from cwd
		run(socketPath) // socket from arg
		content := readDropIn(t, filepath.Join(unit+".d", "10-writables.conf"))
		// ProtectHome relaxation is pinned by the writeExposeDropIn table
		// tests (real /run/user, /home, /root prefixes); the temp-dir socket
		// here intentionally does not trip it.
		for _, want := range []string{"ReadWritePaths=" + project, "ReadWritePaths=" + socketPath} {
			if !strings.Contains(content, want) {
				t.Fatalf("drop-in missing %q:\n%s", want, content)
			}
		}
		if reloads != 2 {
			t.Fatalf("reloads = %d, want one per invocation", reloads)
		}
		// A rerun of an already-exposed path must still reload: it is the
		// only healing path back through this command after a failed reload.
		run()
		if reloads != 3 {
			t.Fatalf("rerun reloads = %d, want the idempotent path to reload too", reloads)
		}
	})

	t.Run("missing unit fails closed", func(t *testing.T) {
		app := NewApp()
		app.euid = func() int { return 0 }
		absent := filepath.Join(t.TempDir(), "absent.service")
		err := app.Execute(context.Background(), []string{"expose", "--unit", absent, "/srv/ghost"}, io.Discard, io.Discard)
		if err == nil || !strings.Contains(err.Error(), "not found") || !strings.Contains(err.Error(), "install.sh") {
			t.Fatalf("err = %v, want a fail-closed installer pointer", err)
		}
	})

	t.Run("failed reload surfaces with the manual remediation", func(t *testing.T) {
		origReload := daemonReload
		t.Cleanup(func() { daemonReload = origReload })
		daemonReload = func(context.Context) error { return errors.New("systemctl daemon-reload failed: no bus") }
		origAvail, origUser := aclAvailable, unitUser
		t.Cleanup(func() { aclAvailable, unitUser = origAvail, origUser })
		aclAvailable = func() bool { return true }
		unitUser = func(context.Context, string) (string, error) { return "root", nil }

		unit := filepath.Join(t.TempDir(), "yukariko.service")
		if err := os.WriteFile(unit, []byte("[Unit]\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		project := t.TempDir()
		if err := os.WriteFile(filepath.Join(project, ".git"), []byte("gitdir: /x\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		app := NewApp()
		app.euid = func() int { return 0 }
		err := app.Execute(context.Background(), []string{"expose", "--unit", unit, project}, io.Discard, io.Discard)
		if err == nil || !strings.Contains(err.Error(), "manually") {
			t.Fatalf("err = %v, want the manual daemon-reload remediation", err)
		}
		// The drop-in was still written; a rerun after the cause is fixed
		// heals (covered by the rerun-heals case above).
		if _, err := os.Stat(filepath.Join(unit+".d", "10-writables.conf")); err != nil {
			t.Fatalf("drop-in missing after failed reload: %v", err)
		}
	})

	t.Run("non-git directory is a usage error", func(t *testing.T) {
		unit := filepath.Join(t.TempDir(), "yukariko.service")
		if err := os.WriteFile(unit, []byte("[Unit]\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		app := NewApp()
		app.euid = func() int { return 0 }
		err := app.Execute(context.Background(), []string{"expose", "--unit", unit, t.TempDir()}, io.Discard, io.Discard)
		if err == nil || !strings.Contains(err.Error(), "git worktree") {
			t.Fatalf("err = %v, want a git-worktree usage error", err)
		}
	})
}

func TestACLCommands(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name     string
		target   string
		isSocket bool
		want     [][]string
	}{
		{
			name:   "home worktree grants traverse then rwX with defaults",
			target: "/home/u/.maomao",
			want: [][]string{
				{"setfacl", "-m", "u:srv:x", "/home/u"},
				{"setfacl", "-R", "-m", "u:srv:rwX", "-m", "d:u:srv:rwX", "/home/u/.maomao"},
			},
		},
		{
			name:     "rootless socket grants traverse then rw",
			target:   "/run/user/1000/docker.sock",
			isSocket: true,
			want: [][]string{
				{"setfacl", "-m", "u:srv:x", "/run/user/1000"},
				{"setfacl", "-m", "u:srv:rw", "/run/user/1000/docker.sock"},
			},
		},
		{
			name:   "system tree needs no traverse grant",
			target: "/srv/proj",
			want: [][]string{
				{"setfacl", "-R", "-m", "u:srv:rwX", "-m", "d:u:srv:rwX", "/srv/proj"},
			},
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got := aclCommands(tc.target, tc.isSocket, "srv")
			if !reflect.DeepEqual(got, tc.want) {
				t.Fatalf("commands = %+v, want %+v", got, tc.want)
			}
		})
	}
}

func TestApplyACLs(t *testing.T) {
	setSeams := func(t *testing.T, user string, avail bool) *[][]string {
		t.Helper()
		var calls *[][]string = &[][]string{}
		origAvail, origUser, origRun := aclAvailable, unitUser, aclRun
		t.Cleanup(func() { aclAvailable, unitUser, aclRun = origAvail, origUser, origRun })
		aclAvailable = func() bool { return avail }
		unitUser = func(context.Context, string) (string, error) { return user, nil }
		record := make([][]string, 0, 2)
		calls = &record
		aclRun = func(_ context.Context, argv []string) error {
			record = append(record, argv)
			return nil
		}
		return calls
	}

	t.Run("grants for the unit user", func(t *testing.T) {
		calls := setSeams(t, "yukariko", true)
		if err := applyACLs(context.Background(), io.Discard, "/run/user/1000/docker.sock", true, "/etc/systemd/system/yukariko.service"); err != nil {
			t.Fatal(err)
		}
		if len(*calls) != 2 || (*calls)[0][3] != "/run/user/1000" {
			t.Fatalf("calls = %+v", *calls)
		}
	})

	t.Run("root unit needs no ACLs", func(t *testing.T) {
		calls := setSeams(t, "root", true)
		if err := applyACLs(context.Background(), io.Discard, "/srv/proj", false, "/etc/systemd/system/yukariko.service"); err != nil {
			t.Fatal(err)
		}
		if len(*calls) != 0 {
			t.Fatalf("root unit ran ACLs: %+v", *calls)
		}
	})

	t.Run("missing setfacl is actionable", func(t *testing.T) {
		setSeams(t, "yukariko", false)
		err := applyACLs(context.Background(), io.Discard, "/srv/proj", false, "/etc/systemd/system/yukariko.service")
		if err == nil || !strings.Contains(err.Error(), "install.sh") {
			t.Fatalf("err = %v, want the installer pointer", err)
		}
	})
}
